language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.8"
install:
  - travis_retry pip install tox coverage
  - travis_retry python setup.py install
script:
  - travis_retry tox

