language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - travis_retry python -m pip install tox 
  - travis_retry python setup.py install
script:
  - travis_retry tox

