language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest ./tests -vv
deploy:
  provider: pypi
  user: __token__
  password:
    secure: CJANTcghMbavXVQhlfM1O+FrhG/APYMxomuZgvQpe+aJbmM/rN03r5Bx1Njs7Wa1ZBFODOfNswjH07bT9XxBtKN2PcrMS0+RIm7UrxtQKySWF6b0VvoMLWkI+Yph00SDCAlUeyieJK8eYh5CUF2OnO/3DLkTuK3ORKWgGUWk2x466OSE8DJlrXUWITl/vUNT4Kwwi6mgQNRAbwDq54+B46EG/QDlGU3x0hdeR42wVHpq3VnGmxjtq94MLFrHJssJyAfevUusRkSvadBCKv1kX0DNXjutA/Whd/HfqC0Z79+V/yZng3bYFZKYKEqdgkc2G25hKg3FSIu07h0y2adf9KXlj9PVSztT29wfB/bZGZEKdTdbTcHZYxh1+XjoBaYWqF/C1huPetCDoILtoyw0iSuZrPcLEEV3IP1uuUNpZOPeUZQUbzVZ5tBoqgtL8H1A9qX+rAYDtO0pgwXMWVL7rnMotItMrjnoRlL/IKGZTwEtDeT+ESu+n8CQzaiq9vlp3GtCXVRDP73cMoGTr0Md/CvyTcoikcp+7HJLNvEfrZXZpZ0U28HSAROETInKAR/GKSQ1btsLKydEuG+ELc3j4zCbbiVgGAoKEPyCgNx6XUeUZ3m2LOz60f/70NIHgspaQgEvkqNwJr3dfZxkq8RFz0nAcyazirCa1cIjY61hNtg=
  distributions: "sdist bdist_wheel"
